# Generated by Django 3.2.4 on 2021-10-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
    ]
