# Generated by Django 3.2.4 on 2021-10-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comment_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_added',)},
        ),
    ]
