# Generated by Django 3.2.4 on 2021-10-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmode',
            name='image',
            field=models.ImageField(default=None, upload_to='myApp/posts/media/'),
        ),
    ]
