# Generated by Django 3.2.4 on 2021-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_postmode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmode',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='myApp/posts/media/'),
        ),
    ]
