# Generated by Django 3.2.4 on 2021-10-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_postmode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmode',
            name='image',
        ),
    ]
