# Generated by Django 3.2.4 on 2021-10-16 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_remove_postmode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmode',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='myApp/posts/media/'),
            preserve_default=False,
        ),
    ]
