# Generated by Django 3.2.4 on 2021-10-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_postmode_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmode',
            name='image',
        ),
    ]
