# Generated by Django 3.2.4 on 2021-10-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_postmode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmode',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
