# Generated by Django 3.2.4 on 2021-08-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
