# Generated by Django 3.2.4 on 2021-08-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(default=True)),
                ('items', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
