# Generated by Django 3.2.4 on 2021-08-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='items',
            field=models.CharField(max_length=100),
        ),
    ]
