# Generated by Django 3.2.4 on 2021-08-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('gametype', models.TextField(max_length=150)),
                ('price', models.DecimalField(decimal_places=1, max_digits=100)),
                ('detail', models.BooleanField(null=True)),
            ],
        ),
    ]
