# Generated by Django 3.2.4 on 2021-08-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='detail',
            new_name='featured',
        ),
    ]
