# Generated by Django 3.2.4 on 2021-09-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sapamode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='', width_field=200)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
