# Generated by Django 3.2.4 on 2021-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapa', '0010_alter_sapamode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapamode',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
